### ISSUE TITLE
Some MAYBE question in megaportrait

### ISSUE THREAD

**Issue by YahooKID** [johndpope/VASA-1-hack#11]
https://github.com/johndpope/MegaPortrait/blob/master/train.py

In original paper, the authors announced that they used AdamW as optimizer but not Adam, it would influence the result in my opinion.

Good Luck

Cheers.

**Comment by johndpope** [comment]
adamW implemented - 
https://github.com/johndpope/MegaPortrait-hack/blob/main/train.py#L138
