### ISSUE TITLE
EMOPortraits - Emotion-enhanced Multimodal One-shot Head Avatars

### ISSUE THREAD

**Issue by johndpope** [johndpope/VASA-1-hack#12]
this will provide resnet warpgenerator code - which i can't anywhere on github.

efforts to recreate it - not yet fruitful
https://github.com/johndpope/MegaPortrait-hack
https://github.com/johndpope/MegaPortrait-hack/blob/main/model.py#L872 =- warpgenerator

Thanks to @neeek2303 for future code drop
https://github.com/neeek2303/EMOPortraits
This repo reserved for official implementation of EMOPortraits: Emotion-enhanced Multimodal One-shot Head Avatars. The code is planned to be released in July 2024.

**Comment by johndpope** [comment]
i got MegaPortraits to train https://github.com/johndpope/MegaPortrait-hack/issues/36
needs some more gpu compute.

**Comment by HumanGamer** [comment]
> needs some more gpu compute.

is there any way i could help? I have a 3090ti in my gaming rig. Probably not enough on it's own, but maybe with some sort of online distributed training, I could share my compute?

**Comment by sanganisahil** [comment]
guys you can use mass compute to train. great work though
