### ISSUE TITLE
Is there a pre-trained model？

### ISSUE THREAD

**Issue by wchuan163** [johndpope/VASA-1-hack#18]
Is there any pre-trained model？

**Comment by johndpope** [comment]
the closest to anything is recreation of the foundation paper that vasa is built on - MegaPortraits
https://github.com/johndpope/MegaPortrait-hack/issues/36
Before throwing more time at this MegaPortrait - EmoPortrait code / model is supposed to drop.
This guy @neeek2303 (who now works at Meta)  was key author of the original samsung paper / so he has definitive code / correct model structure
https://github.com/neeek2303/EMOPortraits

kinda of in a holding pattern for this to drop - then circle back to do diffusion stuff.
I drafted this a while back - https://github.com/johndpope/VASA-1-hack/pulls

more recently been playing around with another microsoft paper
https://github.com/johndpope/IMF
it's stylegan2 based - learned a lot reimplementing this one. 

this week i switch back to stable diffusion.

**Comment by mantrakp04** [comment]
any clude bout emo portrait code?

**Comment by johndpope** [comment]
not sure - the contention was around the warping code 
I actually draft this - warp composition which may be fine
https://github.com/johndpope/MegaPortrait-hack/pull/55
 the direction from imf is working looking into - it claims to transcend warping altogether.
i get stuck on this one
https://github.com/johndpope/IMF/issues/25

while there's interest here - from digging around stable diffusion
from what i can tell - tiktok just cherry pick code from magicdance
https://github.com/Boese0601/MagicDance - has training code

https://github.com/bytedance/X-Portrait - this quality is quite good. but no training code
it maybe possible to retrofit this
https://github.com/Boese0601/MagicDance/issues/43

**Comment by mantrakp04** [comment]
how did you use claude opus to reverse engineer, am curious if we could try improving a model architecture using claude

**Comment by johndpope** [comment]
get the pro subscription and jam in as much RELEVANT content /context - 
code spits out 
ask it a better question
better code spits out.

**Comment by johndpope** [comment]
i did major code merge from fresh code spat out by sonnet. i take another look to train.
