### ISSUE TITLE
voodoo3d. - Egor Zakharov from samsung that worked on megaportraits has new code (coming soon)

### ISSUE THREAD

**Issue by johndpope** [johndpope/VASA-1-hack#2]
https://p0lyfish.github.io/voodoo3d/

https://egorzakharov.github.io/

https://github.com/neeek2303/MegaPortraits/issues/1

**Comment by liutaocode** [comment]
Thanks. But they are different techniques. Voodoo3d is based on NeRF rendering, and Vasa-1 is based on 3D wraping.

**Comment by johndpope** [comment]
good catch. I'm pulling apart the megaportraits code by @kevinfringe and only just seeing the vgg19 stuff under the hood. 

https://github.com/Kevinfringe/MegaPortrait/issues/5

**Comment by Jie-zju** [comment]
> good catch. I'm pulling apart the megaportraits code by @Kevinfringe and only just seeing the vgg19 stuff under the hood.
> 
> [Kevinfringe/MegaPortrait#5](https://github.com/Kevinfringe/MegaPortrait/issues/5)

Hi. Thanks for your reproducing on MegaPortrait and I have learned a lot. However, I confused that using cv. warpPerspective to implement 3D-warping is a right way? Using opencv warpfine on a 4D tensor? what about gradients on it?

**Comment by Jie-zju** [comment]
> good catch. I'm pulling apart the megaportraits code by @Kevinfringe and only just seeing the vgg19 stuff under the hood.
> 
> [Kevinfringe/MegaPortrait#5](https://github.com/Kevinfringe/MegaPortrait/issues/5)

@johndpope 
Hi. Thanks for your reproducing on MegaPortrait and I have learned a lot. However, I confused that using cv. warpPerspective to implement 3D-warping is a right way? Using opencv warpfine on a 4D tensor? what about gradients on it?

**Comment by johndpope** [comment]
@Jie-zju  - you're right. I post findings / fixes from Claude on the associated ticket.

**Comment by wweevv-johndpope** [comment]
I rebuild codebase https://github.com/johndpope/MegaPortrait-hack
