### ISSUE TITLE
Are you planning on training?

### ISSUE THREAD

**Issue by zsxkib** [johndpope/VASA-1-hack#5]
Lmk if you're planning on training, i could maybe help

**Comment by johndpope** [comment]
I want the voxceleb2 - i did do some data loader on my emote-hack repo - i wired it up in a few days 
- https://github.com/johndpope/Emote-hack
- 
in the diffusion transformer architecture- from what I understand- they use patches - and I don’t see those in code (spat out by Claude) 

realistically- better to press for voodoo code to be released. This is kinda just academic excercise.

**Comment by johndpope** [comment]
actually on holiday - away from  workstation with cuda - so can't run this 

- but made tiny bit more progress in necessary calls
https://github.com/johndpope/VASA-1-hack/commit/63c0f44c27fcc01c72450a70b250b387c49d2704
https://github.com/johndpope/VASA-1-hack/blob/main/train_2.py


these edits were from chatgpt - nowdays almost exclusively using claude 

#         # Generate holistic facial dynamics using the diffusion transformer
#         audio_features = batch['audio']
#         gaze_direction = batch['gaze']
#         head_distance = batch['distance']
#         emotion_offset = batch['emotion']

if you look here - claude spat this out - and it seems more closely aligned to VASA paper. 

https://github.com/johndpope/VASA-1-hack/blob/main/train.py
# # Extract keypoints from the generated dynamics
# kp_s = generated_dynamics[:, :, :3]  # Source keypoints
# kp_d = generated_dynamics[:, :, 3:]  # Driving keypoints

# # Compute the rotation matrices
# Rs = torch.eye(3).unsqueeze(0).repeat(kp_s.shape[0], 1, 1)  # Source rotation matrix
# Rd = torch.eye(3).unsqueeze(0).repeat(kp_d.shape[0], 1, 1)  # Driving rotation matrix

# # Call the MotionFieldEstimator
# deformation, occlusion, occlusion_2 = motion_field_estimator(appearance_volume, kp_s, kp_d, Rs, Rd)

have to plug this back in as context to claude.
https://github.com/johndpope/VASA-1-hack/blob/5532d1d2324053900b3a2f73ba2ed9e160fd8b0d/modules/real3d/facev2v_warp/model.py#L137

**Comment by trithucxx** [comment]
> I want the voxceleb2 dataset - doesn’t seem available anymore - torrents are dead. - i did do some data loader on my emote-hack repo - i will wire it up in a few days
> 
> * https://github.com/johndpope/Emote-hack
> 
> in the diffusion transformer architecture- from what I understand- they use patches - and I don’t see those in code (spat out by Claude)
> 
> realistically- better to press for voodoo code to be released. This is kinda just academic excercise.

I have been downloaded, still work. Anw, how can I start/run your project bro?

**Comment by johndpope** [comment]
Hi @trithucxx -  

I'm looking at booting up MegaPortrait by upgrading the training for this repo - https://github.com/johndpope/MegaPortrait/
@kevinFringe had used a couple of directories - but I have some code in the works with decord / mp4s 
https://github.com/johndpope/Emote-hack/blob/main/Net.py#L1085


For now - this model  **Eapp1** needs to be 100% - otherwise everything else isn't going to work. 
Or maybe this volumetric can be sourced from other repo? 
can this do it? IDK - https://real3dportrait.github.io/


 **This is the first part of the Appearance Encoder. To generate a 4D tensor of volumetric features vs.**
https://github.com/johndpope/MegaPortrait/blob/master/model.py#L82

**Comment by trithucxx** [comment]
> Hi @trithucxx -
> 
> I'm looking at booting up MegaPortrait by upgrading the training for this repo - https://github.com/johndpope/MegaPortrait/ @Kevinfringe had used a couple of directories - but I have some code in the works with decord / mp4s https://github.com/johndpope/Emote-hack/blob/main/Net.py#L1085
> 
> For now - this model **Eapp1** needs to be 100% - otherwise everything else isn't going to work. Or maybe this volumetric can be sourced from other repo? can this do it? IDK - https://real3dportrait.github.io/
> 
> **This is the first part of the Appearance Encoder. To generate a 4D tensor of volumetric features vs.** https://github.com/johndpope/MegaPortrait/blob/master/model.py#L82
> 
> UPDATE Im pretty sure we can piggy back off the VOODOO3D paper (code in june)
> 
> * even though it's for NERF.
>   https://arxiv.org/pdf/2312.04651
> 
> <img alt="Screenshot 2024-04-29 at 10 14 18 pm" width="395" src="https://private-user-images.githubusercontent.com/289994/326432081-3ccf44a3-4a65-4975-8bb8-b0462024812d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODgwNTEsIm5iZiI6MTcxNDQ4Nzc1MSwicGF0aCI6Ii8yODk5OTQvMzI2NDMyMDgxLTNjY2Y0NGEzLTRhNjUtNDk3NS04YmI4LWIwNDYyMDI0ODEyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNDM1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzM4YWU2NDBmMmU1ODNjNTVkNjczOWRmNTk0YzFhMzc1YTMzMTFmOTM3ZTI0NWM5MTMyYmQ2ODA5YmVkODA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dHS5YVwKC9g_WAqDM7KHFH0TUM812c4EAL36CG6kaIE">

I tested real3dportrait, it's seems to be inaccurate and the video take 3h for 2m [talking vid](https://youtu.be/yEKTrJjfcfM) completion time (too long). How about torrent you can not download. Hope to see your project run.

**Comment by johndpope** [comment]
so a few days ago i was looking at some other code - basically claude thinks there's enough to avoid needing the megaportrait code - specifically the  4D tensor of volumetric features
this supposedly handles it.

`   self.appearance_extractor = AppearanceFeatureExtractor()
`
```python

class AppearanceFeatureExtractor(nn.Module):
    # 3D appearance features extractor
    # [N,3,256,256]
    # [N,64,256,256]
    # [N,128,128,128]
    # [N,256,64,64]
    # [N,512,64,64]
    # [N,32,16,64,64]
    def __init__(self, model_scale='standard'):
        super().__init__()
        use_weight_norm = False
        down_seq = [64, 128, 256]
        n_res = 6
        C = 32
        D = 16
        self.in_conv = ConvBlock2D("CNA", 3, down_seq[0], 7, 1, 3, use_weight_norm)
        self.down = nn.Sequential(*[DownBlock2D(down_seq[i], down_seq[i + 1], use_weight_norm) for i in range(len(down_seq) - 1)])
        self.mid_conv = nn.Conv2d(down_seq[-1], C * D, 1, 1, 0)
        self.res = nn.Sequential(*[ResBlock3D(C, use_weight_norm) for _ in range(n_res)])

        self.C, self.D = C, D

    def forward(self, x):
        x = self.in_conv(x)
        x = self.down(x)
        x = self.mid_conv(x)
        N, _, H, W = x.shape
        x = x.view(N, self.C, self.D, H, W)
        x = self.res(x)
        return x

```

**Comment by johndpope** [comment]
@francqz31 i agree with most of your thoughts. The world will be different place when gpt5 drops.  I’d add - don’t use chatgpt4 / use opus - and if the code it’s spitting out is / or feels off / discard the chat and start a fresh with updates. Eg base code + paper / increment logic / llm goes off on wrong tangent / discard chat / feed it updated code and even given it more context / header files or relevant code form other repos etc.



WRT training - I had mentioned that I’d need to get megaportrait code working - I have an update.  The jury is still out until training - but I believe opus has solved a key warping problem with megaportraits (as explained in readme - https://github.com/Kevinfringe/MegaPortrait) 

details here
https://github.com/Kevinfringe/MegaPortrait/issues/5

**Comment by johndpope** [comment]
ok - so took me a month - but i believe i got the dependent paper MegaPortraits implmented.
https://github.com/johndpope/MegaPortrait-hack/tree/main
there's actually going to be a new code upgrade/ with video data from FB dropping in July 24 - https://github.com/neeek2303/EMOPortraits

i am running local training on a couple of videos 
https://github.com/johndpope/MegaPortrait-hack/pull/21

the interesting thing with this paper is - there's no keypoints - it's all resnet feature maps with warping.
**UPDATE**
running some numbers passed chatgpt - 250 seconds / epoch - 200,000 epochs will take like 2 years on 3090. / 2 months on a h100.

**Comment by fenghe12** [comment]
do u still need talking head video dataset？we collected some

**Comment by johndpope** [comment]
hi @fenghe12  - 
sorry for late reply - been distracted recreating code for this paper - https://arxiv.org/pdf/2405.07257
https://github.com/johndpope/SPEAK-hack

I would appreciate any help in cross checking code with paper.
I include some test inference code 

if you want to share link to videos - happy to grab them.

**Comment by johndpope** [comment]
this paper by Microsoft - Implicit Motion Function
https://openaccess.thecvf.com/content/CVPR2024/papers/Gao_Implicit_Motion_Function_CVPR_2024_paper.pdf

I recreate here
https://github.com/johndpope/IMF

(assume it's all wrong -i had to switch in ResNets as feature extractor (it's not mentioned in paper)  yet it seems to be converging)
https://wandb.ai/snoozie/IMF/runs/f9o9vvje?nw=nwusersnoozie

**Comment by johndpope** [comment]
latest claude updates maybe very close to working / trainable model.

**Comment by johndpope** [comment]
Hey - Sakib,

i am now planning on training - is this something you can help with? 
 https://wandb.ai/snoozie/vasa-overfitting/runs/qqprlbs6?nw=nwusersnoozie
